function Hd = mi_filtro_coef_2
%MI_FILTRO_COEF_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 18-Apr-2019 23:28:32

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 12800000;  % Sampling Frequency

Fstop1 = 1240000;          % First Stopband Frequency
Fpass1 = 1270000;          % First Passband Frequency
Fpass2 = 1290000;          % Second Passband Frequency
Fstop2 = 1320000;          % Second Stopband Frequency
Dstop1 = 0.01;             % First Stopband Attenuation
Dpass  = 0.057563991496;  % Passband Ripple
Dstop2 = 0.01;             % Second Stopband Attenuation
dens   = 16;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
